#!/bin/sh

colors=$(./getcolors "$1")

options() {
    printf 'using ($3==%d?$1:1/0):2 notitle pt 5 ps 0.5' "$1"
}

printf "plot '%s' " "$1"
options 1
for color in $(seq 2 "$colors"); do
    printf ", '' "
    options "$color"
done

printf '\n'

